server:
  port: ${PORT:8081}
# Configurações de transação
spring:
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        enable_lazy_load_no_trans: true
        transaction:
          auto_close_session: true
