server:
  port: 8080
spring:
  cloud:
    gateway:
#      default-filters:
#        - name: LogFilter
      routes:
        - id: animalRoute
          uri: lb://ANIMAL-SERVICE
          predicates:
            - Path=/animal/**
#          filters:
#            - name: SubscriptionFilter
        - id: specieRoute
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/specie/**
          filters:
            - AddRequestHeader=animal-request-header, custom-animal-request-header
            - AddResponseHeader=animal-response-header, custom-animal-response-header
